name: iotflixcinema
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # social sign in
  google_sign_in: ^5.0.7
  flutter_facebook_login: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.3
  google_fonts: ^2.0.0


  # utility
  shimmer: ^2.0.0
  share: ^2.0.4
  validators: ^3.0.0

  #microframwork for state management
  #get: ^4.3.8
  get_storage: ^2.0.3
  shared_preferences: ^2.0.7

  #view
  shape_of_view: ^1.0.2
  flutter_responsive_screen: ^1.0.0
  font_awesome_flutter: ^9.1.0
  #webview_flutter: ^2.0.7
  flutter_inappwebview: ^5.3.2

  #image
  image_picker: ^0.8.3+3
  extended_image: ^4.1.0
  flutter_svg: ^0.22.0

  #VEDIO PLAYER
  better_player: ^0.0.73
  youtube_player_flutter: ^8.0.0

  #page indicator
  smooth_page_indicator: ^0.2.3

  url_launcher: ^6.0.9

  #toast
  toast: ^0.1.5

  #http
  http: ^0.13.3
  dio: ^4.0.0
  http_parser: ^4.0.0
  flutter_slidable: ^0.6.0
  flutter_html: ^2.1.1

  #scroll
  scroll_to_index: ^2.0.0
  pull_to_refresh: ^2.0.0

  #ads
  #google_mobile_ads: ^0.12.1+1
  #facebook_audience_network: ^0.9.0
  #unity_ads_plugin: ^0.2.3
  #flutter_native_admob: ^2.1.0+3
  #admob_flutter: ^1.0.1

  #one signal
  #onesignal_flutter: ^3.2.1

  #deep lonking
  uni_links: ^0.5.1
  #downloader
  #flutter_downloader: ^1.7.3
  path_provider: ^2.0.2
  permission_handler: ^8.0.0+2
  android_path_provider: ^0.2.1
  #encrypt
  aes_crypt: ^0.1.1
  encrypt: ^5.0.1
  flutter_secure_storage: ^4.2.1
  #background
  flutter_background_service: ^0.1.5

  device_info: ^2.0.2
  #advertising_id: 2.0.0
  get: 4.5.1

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
    - icons/
    - assets/svg/
    - assets/images/countries/
    #- assets/images/genre/
    - assets/images/app_image/
    - assets/images/explore_page/
    #- assets/images/actress/
    - assets/images/splash/
    - assets/images/help_and_feedBack/
    - assets/images/video_quality/
    - assets/images/place_holders/
    - assets/images/payment/
    - assets/images/sign_in_image.svg
    - assets/images/no_data_found.png
    - assets/images/no_data_found_dark.png


  fonts:
    - family: poppins_bold
      fonts:
        - asset: fonts/poppins_bold.ttf
    - family: poppins_medium
      fonts:
        - asset: fonts/poppins_medium.ttf
    - family: poppins_regular
      fonts:
        - asset: fonts/poppins_regular.ttf
    - family: poppins_semibold
      fonts:
        - asset: fonts/poppins_semibold.ttf
    - family: BottomIcon
      fonts:
        - asset: icons/BottomIcon.ttf
    - family: SubScriptionIcons
      fonts:
        - asset: assets/icons/SubScriptionIcons.ttf
    - family: ExploreIcons
      fonts:
        - asset: assets/icons/ExploreIcons.ttf


